# Generated by Django 3.2.7 on 2021-09-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Received contact forms'},
        ),
    ]
